queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: Hey @{{author}}! This PR has merge conflicts. Please fix them before continuing review.
      label:
        add:
          - conflict

  - name: Remove conflicts label when conflicts gone
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: Notify author when merge queue failed
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: |
          Merge failed. Please see automated check logs for more details.
  
  - name: automatic update prs
    conditions:
      - -conflict
      - -draft
      - label="do-not-merge"
      - 'base=master'
    actions:
      update:

