name: Publish Packages

on:
  workflow_run:
    workflows:
      - Generate Token List
    types: [completed]
    branches: [master]

jobs:
  publish-bot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: 'true'
          scope: '@eth-optimism'

      - name: Install dependencies to prepare for release 🔧
        run: yarn

      - name: Build and publish package on NPM 📦
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
