name: Publish Packages

on:
  workflow_run:
    workflows:
      - Generate Token List
    types: [completed]
    branches: [master]

jobs:
  publish-bot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29
        with:
          files: |
            bin/**
            src/bot.ts
            package.json
            yarn.lock
            Dockerfile.bot

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ethereumoptimism/tokenlist-bot:latest

      - name: Install dependencies to prepare for release 🔧
        run: yarn

      - name: Build and publish package on NPM 📦
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
